### ISSUE TITLE
Matlab

### ISSUE THREAD

**Issue by EdwinFoppa** [Dubbeldenkan/NeoFinans#1]
Jag har inte matlab så just nu är det lite svårt att vara helt delaktig, men tycker ändå det är rätt sätt att fortsätta utvecklingen på. Jag kan möjligtvis göra uppgiffter utanför, som att hitta statistik och annat.

**Comment by Dubbeldenkan** [comment]
Du kan ju ladda ner matlab från någon hemsida på skolan

Skickat från min iPhone

**Comment by Dubbeldenkan** [comment]
För att ladda ner och aktivera Matlab, gå in på www.mathworks.com där du registrerar dig och skapar konto. Använd din mejladress [namn]@student.liu.se vid registreringen och ange att programmet skall användas för "Academic use". För nedladdning av önskad version är det sedan bara att följa länk till nedladdningssidorna. Efter att du hämtat programmet skall det installeras och aktiveras, en aktiveringskod (Activation Key) skall anges i samband med installationen och den är samma för alla versioner nämligen: 84255-57849-04496-09821-54890. För att detta skall fungera skall datorn vara ansluten till Internet under installationen. 

Skickat från min iPhone
